name: cellranger-snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.1
  - aiosignal=1.3.2
  - amply=0.1.6
  - appdirs=1.4.4
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=25.3.0
  - bcftools=1.6
  - bcrypt=3.2.2
  - boto3=1.38.43
  - botocore=1.38.43
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - cachetools=5.5.2
  - certifi=2025.7.14
  - cffi=1.15.0
  - charset-normalizer=2.1.1
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.6
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.10
  - colorama=0.4.6
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - cryptography=45.0.3
  - curl=8.14.1
  - datrie=0.8.2
  - defusedxml=0.7.1
  - docutils=0.21.2
  - dpath=2.2.0
  - dropbox=12.0.2
  - eido=0.2.4
  - exceptiongroup=1.3.0
  - expat=2.7.1
  - filechunkio=1.8
  - frozenlist=1.3.0
  - ftputil=5.1.0
  - gitdb=4.0.12
  - gitpython=3.1.44
  - google-api-core=2.25.1
  - google-api-python-client=2.173.0
  - google-auth=2.40.3
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - grpcio=1.71.0
  - h2=4.2.0
  - hpack=4.1.0
  - htslib=1.22
  - httplib2=0.22.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - jinja2=3.1.6
  - jmespath=1.0.1
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=15.1.0
  - libgrpc=1.71.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.20
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.38.1
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - logmuse=0.2.8
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.1
  - mdurl=0.1.2
  - multidict=6.0.2
  - nbformat=5.10.4
  - ncurses=6.5
  - numpy=1.22.3
  - oauth2client=4.1.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=1.4.2
  - paramiko=3.5.1
  - peppy=0.40.7
  - pip=25.1
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.5
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - ply=3.11
  - prettytable=3.16.0
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - psutil=5.9.1
  - pthread-stubs=0.3
  - pulp=2.7.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.2
  - pynacl=1.5.0
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=8.4.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-irodsclient=2.1.0
  - python_abi=3.10
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - reretry=0.11.8
  - rich=14.0.0
  - rpds-py=0.22.3
  - rsa=4.9.1
  - s3transfer=0.13.0
  - samtools=1.22
  - seqkit=2.10.0
  - setuptools=78.1.1
  - setuptools-scm=8.3.1
  - six=1.17.0
  - slacker=0.14.0
  - smart_open=7.1.0
  - smmap=5.0.2
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - sqlite=3.50.1
  - stone=3.3.2
  - stopit=1.1.2
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.2.1
  - toposort=1.10
  - traitlets=5.14.3
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ubiquerg=0.8.0
  - uritemplate=4.2.0
  - urllib3=2.5.0
  - veracitools=0.1.3
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.14.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.7.2
  - yte=1.8.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - cellranger-snakemake==1.0.0
      - colored==2.3.0
