name: snakemake8
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adwaita-icon-theme=49.0
  - amply=0.1.6
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - argparse-dataclass=2.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - bcftools=1.22
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - conda-inject=1.3.2
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - cpp-expected=1.3.1
  - dbus=1.16.2
  - docutils=0.22.4
  - dpath=2.2.0
  - eido=0.2.4
  - epoxy=1.5.10
  - exceptiongroup=1.3.1
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib-tools=2.86.3
  - graphite2=1.3.14
  - graphviz=14.1.0
  - gsl=2.7
  - gtk3=3.24.43
  - gts=0.7.6
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - htslib=1.22.1
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=78.1
  - idna=3.11
  - immutables=0.21
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libarchive=3.8.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.1
  - libmamba=2.4.0
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.53
  - librsvg=2.60.0
  - libsolv=0.7.35
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - logmuse=0.2.8
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.4.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - nbformat=5.10.4
  - ncurses=6.5
  - nlohmann_json-abi=3.12.0
  - numpy=2.4.0
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - pcre2=10.47
  - pephubclient=0.4.4
  - peppy=0.40.8
  - perl=5.32.1
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - psutil=7.2.1
  - pthread-stubs=0.4
  - pulp=2.8.0
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.3.1
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.3
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - readline=8.3
  - referencing=0.37.0
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - reretry=0.11.8
  - rich=14.2.0
  - rpds-py=0.30.0
  - samtools=1.22.1
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=4.2.4
  - six=1.17.0
  - slack-sdk=3.39.0
  - slack_sdk=3.39.0
  - smart_open=7.5.0
  - smmap=5.0.2
  - snakemake=9.14.5
  - snakemake-interface-common=1.22.0
  - snakemake-interface-executor-plugins=9.3.9
  - snakemake-interface-logger-plugins=2.0.0
  - snakemake-interface-report-plugins=1.3.0
  - snakemake-interface-scheduler-plugins=2.0.2
  - snakemake-interface-storage-plugins=4.3.2
  - snakemake-minimal=9.14.5
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.3.0
  - traitlets=5.14.3
  - typer=0.21.0
  - typer-slim=0.21.0
  - typer-slim-standard=0.21.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ubiquerg=0.8.0
  - urllib3=2.6.2
  - veracitools=0.1.3
  - wayland=1.24.0
  - wheel=0.45.1
  - wrapt=1.17.3
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2025.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yte=1.9.4
  - zstd=1.5.7
  - pip:
      - cellranger-snakemake==2.0.0
      - snakemake-executor-plugin-slurm==2.0.3
      - snakemake-executor-plugin-slurm-jobstep==0.3.0
